#!/bin/bash
# ============================================================================
# AudioMedic - Guia Interativo de Deploy VPS
# ============================================================================

echo "═══════════════════════════════════════════════════════════════"
echo "        AudioMedic - Deploy em VPS Hostinger Privado"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "Este guia vai te ajudar a fazer o deploy completo no seu VPS."
echo ""

# Check if running on VPS or local
if [ ! -d "/var/www" ]; then
    echo "⚠️  Parece que você está rodando localmente."
    echo ""
    echo "📋 CHECKLIST PRÉ-DEPLOY:"
    echo ""
    echo "1. VPS Contratado:"
    echo "   - [ ] VPS Hostinger ativo"
    echo "   - [ ] IP público recebido"
    echo "   - [ ] Acesso SSH configurado"
    echo ""
    echo "2. Domínio:"
    echo "   - [ ] Domínio registrado"
    echo "   - [ ] DNS apontando para IP do VPS"
    echo "   - [ ] Propagação DNS completa (pode levar 24h)"
    echo ""
    echo "3. MongoDB:"
    echo "   - [ ] MongoDB Atlas conta criada (recomendado)"
    echo "   - [ ] Cluster gratuito M0 criado"
    echo "   - [ ] Connection string obtido"
    echo ""
    echo "4. API Keys:"
    echo "   - [ ] OPENAI_API_KEY ou EMERGENT_LLM_KEY disponível"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "📤 PRÓXIMO PASSO: Upload para VPS"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "Opção A: Via Git (Recomendado)"
    echo "-------------------"
    echo "1. Faça commit do projeto:"
    echo "   git init"
    echo "   git add ."
    echo "   git commit -m 'AudioMedic v2.0'"
    echo ""
    echo "2. Push para GitHub/GitLab"
    echo ""
    echo "3. No VPS, clone:"
    echo "   ssh root@SEU-IP"
    echo "   cd /var/www"
    echo "   git clone https://github.com/seu-usuario/audiomedic.git"
    echo ""
    echo "Opção B: Via SCP"
    echo "-------------------"
    echo "1. Comprimir projeto (exclua node_modules e venv):"
    echo "   tar -czf audiomedic.tar.gz --exclude='node_modules' --exclude='venv' --exclude='.git' ."
    echo ""
    echo "2. Upload para VPS:"
    echo "   scp audiomedic.tar.gz root@SEU-IP:/var/www/"
    echo ""
    echo "3. No VPS, extrair:"
    echo "   ssh root@SEU-IP"
    echo "   cd /var/www"
    echo "   mkdir audiomedic && cd audiomedic"
    echo "   tar -xzf ../audiomedic.tar.gz"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "🚀 DEPOIS DO UPLOAD:"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "Execute no VPS:"
    echo ""
    echo "  cd /var/www/audiomedic"
    echo "  chmod +x deploy_hostinger.sh"
    echo "  ./deploy_hostinger.sh"
    echo ""
    echo "O script vai instalar tudo automaticamente!"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    
else
    echo "✅ Detectado ambiente VPS!"
    echo ""
    echo "═══════════════════════════════════════════════════════════════"
    echo "🚀 INSTALAÇÃO AUTOMÁTICA"
    echo "═══════════════════════════════════════════════════════════════"
    echo ""
    echo "O script deploy_hostinger.sh vai:"
    echo ""
    echo "  1. ✅ Instalar Python 3.11"
    echo "  2. ✅ Instalar Node.js 18"
    echo "  3. ✅ Instalar Nginx"
    echo "  4. ✅ Instalar Supervisor"
    echo "  5. ✅ Configurar backend (venv, requirements)"
    echo "  6. ✅ Configurar frontend (build)"
    echo "  7. ✅ Configurar Supervisor"
    echo "  8. ✅ Configurar Nginx"
    echo "  9. ✅ Configurar Firewall"
    echo "  10. ✅ Instalar SSL (Certbot)"
    echo ""
    
    read -p "Deseja executar o deploy automático agora? (s/n): " response
    
    if [ "$response" = "s" ] || [ "$response" = "S" ]; then
        echo ""
        echo "Executando deploy..."
        chmod +x deploy_hostinger.sh
        ./deploy_hostinger.sh
    else
        echo ""
        echo "OK! Execute manualmente quando estiver pronto:"
        echo "  ./deploy_hostinger.sh"
    fi
fi

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "📚 DOCUMENTAÇÃO DISPONÍVEL:"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  • MIGRATE_TO_VPS.md          - Guia de migração (este guia)"
echo "  • DEPLOY_HOSTINGER.md        - Guia completo VPS (detalhado)"
echo "  • DEPLOY_CHECKLIST.md        - Checklist de deploy"
echo "  • deploy_hostinger.sh        - Script automático"
echo "  • verify_deploy.sh           - Verificar após deploy"
echo ""
echo "═══════════════════════════════════════════════════════════════"
